### ISSUE TITLE
downloaded data corrupted

### ISSUE THREAD

**Issue by davidsands** [brandon-rhodes/pycon-pandas-tutorial#14]
Whoops. Not corrupted, just very different from the original data used in the PyCon demonstration. 

(I would delete this issue, but don't seem to have that option).

**Comment by brandon-rhodes** [comment]
Do you have a single example you could share, of a result that is coming out differently? Maybe I could schedule an annual update to the tutorial materials so that the answers do not drift too far from the data coming from IMDB!

**Comment by davidsands** [comment]
The IMDB data is fine, but there seems to be a problem with the notebook viewer, which caused me to think that data was corrupted. (Also, the actual actor names have dollar signs in them, which I wasn't expecting.) Here are a couple of screen-shots of what "Solutions-1" looks like in Firefox and Google Chrome on Ubuntu 14.04.

![screenshot_2016-03-31_16-37-48](https://cloud.githubusercontent.com/assets/610089/14170550/ec4e6c1e-f760-11e5-84a2-2db3246eecb2.png)
![screenshot_2016-03-31_16-41-20](https://cloud.githubusercontent.com/assets/610089/14170605/3b915c28-f761-11e5-8da0-06c018000ab0.png)

**Comment by brandon-rhodes** [comment]
Yes, I also had not known that actor names can have dollar signs in them!

http://www.imdb.com/name/nm0790001/

It does look like the dollar sign is confusing the rendering of your HTML. Try this: instead of saying just

```
cast.head()
```

instead try outputting it as plain text with `print()`:

```
print(cast.head())
```

If the `print()` version works fine, then I think this is a bug with the notebook viewer. If the `print()` version has these extra angle brackets and raw HTML code inside, then it may be a problem I have to tackle with the data. Thanks for the screenshots, this makes your issue much clearer!

**Comment by iaindinw** [comment]
Just for information, I am having similar issues on windows (that probably complicates rather than helps). I tried printing but has doesn't appear to fix the problem so it may be the data. I'm using python 3 so the default encoding is already UTF-8 and there aren't any errors, just some weird results!

I'd also just like to say thank you for the fantastic tutorial, it really is excellent!

![image](https://cloud.githubusercontent.com/assets/18350007/14385591/36e39e00-fd99-11e5-807a-87b524aa3664.png)

**Comment by brandon-rhodes** [comment]
Those question marks are, alas, deliberate:

https://github.com/brandon-rhodes/pycon-pandas-tutorial/blob/master/build/BUILD.py#L220

They are how I handle actors and actresses with accented characters in their names, since my early attempts to get their Unicode characters to render correctly resulted in terrible errors under Windows when the tutorial was run with Python 2. As long as I want to support that combination — and at the moment I do — we need some stand-in character for the unprintable ones.

Maybe someday I should use two-character combinations, like `'A` for Á and so forth, and welcome a contribution that would accomplish that — but for now I am going to stick with the `?` since it was quick and seems to make everything work.

Sorry that the special-character handling looked confusing!
