### ISSUE TITLE
BUILD.py doesn't work

### ISSUE THREAD

**Issue by foreroa** [brandon-rhodes/pycon-pandas-tutorial#17]
BUILD.py doesn't work, and I've wasted at least an hour trying to convert your gz files into csv file.

Why can't you just make the csv files directly available in your github and not make us go throught this whole rigamarole?

Thanks,

**Comment by brandon-rhodes** [comment]
I cannot make CSV files available because the IMDB owns the data and does not allow redistribution.

http://www.imdb.com/interfaces

If you have encountered an error, please paste the error and I will be happy to advise you about what may be going wrong.

**Comment by VijayKodibailu** [comment]
BUILD.py not found inside /build/ folder there is only BUILD.sh


Thanks and regards

**Comment by brandon-rhodes** [comment]
Your checkout of this repository must have failed partway through, or else must have become damaged, because GitHub shows a `BUILD.py` inside the build folder:

https://github.com/brandon-rhodes/pycon-pandas-tutorial/tree/master/build

Try a fresh checkout and verify that the file is there before trying again, maybe?

**Comment by brandon-rhodes** [comment]
I am going to close this for now, but feel free to re-open if you figured out more about what was going on but your problem is not solved yet!
