### ISSUE TITLE
Guidence for completing the ground-up learning..

### ISSUE THREAD

**Issue by ghost** [brandon-rhodes/pycon-pandas-tutorial#21]
Hi,
From your experience, is there an advice or recommendation with a book or course that could significantly help in building over the ground knowledge I have built through your lecture and exercise materials? or just work through problems and discover from the library documentation?
Is there an advice from your learning experience I should care about so I could reach the easy organized understanding of the information like that you introduced in your lecture which I rarely and hardly get?
Thanks,

**Comment by brandon-rhodes** [comment]
I myself, alas, learned Pandas through a few online examples followed by long and extensive reading in its API documentation, so I cannot recommend any books because I did not myself use one. (There were few books out on Pandas when I started learning it!) You might want to look on YouTube for other introductions to Pandas and data processing — I think that a few more have been given at PyCon itself, as well as at some of the PyData conferences, and maybe some of them would explain Pandas in a way that fills in some of the gaps in my own presentation. I hope you have good luck!
