### ISSUE TITLE
i also have error when python Build.py

### ISSUE THREAD

**Issue by damvantai** [brandon-rhodes/pycon-pandas-tutorial#28]
Reading "genres.list.gz" to find interesting movies
Found 235702 titles
Writing "titles.csv"
Finished writing "titles.csv"
Reading release dates from "release-dates.list.gz"
Finished writing "release_dates.csv"
Reading 'actors.list.gz'
Traceback (most recent call last):
  File "build/BUILD.py", line 224, in <module>
    main()
  File "build/BUILD.py", line 119, in main
    for line in lines:
  File "/usr/lib/python2.7/gzip.py", line 464, in readline
    c = self.read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xcf2f2e89 != 0xf6d69ce7L

**Comment by brandon-rhodes** [comment]
That usually indicates that a network error during the download of the file has added incorrect bytes in the middle, so that gzip cannot recover the file's original content. Could you try removing the file and downloading it again? Over a noisy or slow Internet, I sometimes have needed several tries before a big file would arrive intact. (If you can fetch over HTTPS instead, that tends to do much better at detecting and correcting network errors.)
