### ISSUE TITLE
Where to download data?

### ISSUE THREAD

**Issue by pcuci** [brandon-rhodes/pycon-pandas-tutorial#3]
I can't find the instructions to download the data: titles.csv and cast.csv - any hints?

**Comment by pcuci** [comment]
Also the slides are not available at https://speakerdeck.com/pycon2015 as advertised here: https://www.youtube.com/watch?v=5JnMutdy6Fw

**Comment by brandon-rhodes** [comment]
I have removed the files because, after read-reading the IMDB conditions of service, I realize that I lack permission to re-distribute their data as my own CSV files, and that each person checking out the tutorial should rebuild the data files themselves. Tonight or tomorrow I will add instructions to a README, and fix up the build scripts for others’ use, so that everyone can re-create the database themselves without running afoul of the legal problem of redistribution.

As for the YouTube links: I have no idea what to do. :) The second link in their description is simply broken and beyond my power to fix. The first, to speakerdeck, is problematic because there were no slides for this tutorial: the notebooks are really what carried the weight of the presentation. At some point I will see if the people with the YouTube password can remove those broken links to prevent confusion.

**Comment by brandon-rhodes** [comment]
Oh — and, links:

http://www.imdb.com/interfaces
http://www.imdb.com/help/show_leaf?usedatasoftware

**Comment by pcuci** [comment]
The build script to regenerate the IMDB data would be fantastic.

I'm enjoying your talk, looking forward to the practice.

**Comment by gmhoward** [comment]
Thanks for putting together the Pandas tutorial, really nice to get a good feeling for what one can do with Pandas.

Appreciate the interfaces links shared above. Can you identify the files used to come up with the title.csv and cast.csv, so we can recreate them from the IMDB site? Thanks,

**Comment by brandon-rhodes** [comment]
To avoid the problems with non-ASCII characters that several users reported during the tutorial event itself, I have completely re-written the routine that generates the data files, and updated the README that is displayed on the front page of this repository. Please try following its instructions and see if it gets you up and running. If not, open an issue reporting your problem with the new data build process and I will work to get it resolved!
