### ISSUE TITLE
Exercise 6 Title Casing the 'title' column in cleanup

### ISSUE THREAD

**Issue by samgutentag** [brandon-rhodes/pycon-pandas-tutorial#33]
Working through Exercise 6, title casing the 'title' column in the final dataframe (or in the sales2 dataframe) is useful to catch the the difference between 'Pining For The Fisheries of Yore' in sales1 and 'Pining for the Fisheries of Yore' in sales2

```
# title case 'title' column
df['title'] = df['title'].str.title()
```

**Comment by brandon-rhodes** [comment]
Thanks for pointing that out! I obviously made the book titles slightly different to invite this fix, but then failed to carry it through in the exercises. I'll commit a fix — probably using `lower()` since it might confuse students to see `title` meaning two quite different things in the same line of code.

Thanks again!

**Comment by samgutentag** [comment]
ah that is a good point! thanks again so much for these tutorials!
