### ISSUE TITLE
Leading couple

### ISSUE THREAD

**Issue by cjer** [brandon-rhodes/pycon-pandas-tutorial#36]
Hey, 
Great tutorial!
finished all exercised and is playing around some more with the data.
Trying to figure out credits for the leading couple (n=1, and n=2), seeing their actor/actress distribution across the years. Solved it this way:
```python
c = cast
c = c[c.n <= 2]
m = c.merge(c, on=['title', 'year'])
m = m[(m.n_y != m.n_x) & (m.n_x==1.0)]
quad = m.groupby(['year','type_x', 'type_y']).size().unstack().unstack().fillna(0)
quad['totals'] = quad['actor', 'actor'] + quad['actor', 'actress'] + quad['actress', 'actor'] + quad['actress', 'actress']
quad['actor', 'actor'] = quad['actor', 'actor'] / quad['totals']
quad['actor', 'actress'] = quad['actor', 'actress'] / quad['totals']
quad['actress', 'actor'] = quad['actress', 'actor'] / quad['totals']
quad['actress', 'actress'] = quad['actress', 'actress'] / quad['totals']
quad.drop(['totals'], axis=1).plot(ylim=(0,1), xlim=(1915,2019))
quad.totals.sum()
```
The sum of totals here is significantly larger than this amount:
```python
len(cast[(cast.n <= 2)].groupby('title'))
```
I'm struggling to figure out why. Would love some guidance :)

Thanks!
Dan

**Comment by brandon-rhodes** [comment]
Running `groupby('title')` simply rearranges the dataframe, I think? So you're measuring the `len()` of the list of cast members you've made, which I'd guess would be roughly twice the number of movies. Whereas your earlier numbers may count movies rather than actors. Let me know if that doesn't explain the difference!
