### ISSUE TITLE
Can't convert the data

### ISSUE THREAD

**Issue by aidiss** [brandon-rhodes/pycon-pandas-tutorial#4]
This is the error that I get:

```
C:\Users\user\Desktop\pycon-pandas-tutorial-master\build>python build.py
Traceback (most recent call last):
  File "build.py", line 221, in <module>
    main()
  File "build.py", line 12, in main
    os.chdir(os.path.dirname(__file__))
OSError: [WinError 123] The filename, directory name, or volume label syntax is
incorrect: ''
```

**Comment by UTEMScripts** [comment]
Hope I am not beating a dead horse, I get a different error:

---

  C:...\pycon-pandas-tutorial> python build/BUILD.py
    File "./build/BUILD.py", line 4
      <!DOCTYPE html>
      ^
  SyntaxError: invalid syntax

---

**Comment by brandon-rhodes** [comment]
@aidiss — Interesting! Try editing the file to alter the line as follows:

```
os.chdir(os.path.dirname(os.path.abspath(__file__)))
```

Does that fix the problem?

@saintsfan342000 — It looks like you might have copied a complete different file atop `BUILD.py` because the version of `BUILD.py` here in the repository does not say "DOCTYPE" anywhere on line 4:

https://github.com/brandon-rhodes/pycon-pandas-tutorial/blob/master/build/BUILD.py

You might want to try a fresh download, since I cannot guess what might have replaced `BUILD.py` with another file that has a "DOCTYPE" inside of it as though it is HTML!

**Comment by UTEMScripts** [comment]
Thanks!  I realize now what probably happened:
From this directory, https://github.com/brandon-rhodes/pycon-pandas-tutorial/tree/master/build
simply right-clicking BUILD.py and Save Link As (using Firefox) doesn't download the file.  Rather, it saves the webpage.  So what I had was HTML source.

Sorry for wasting your time.  Looking forward to the exercises.

**Comment by aidiss** [comment]
@brandon-rhodes - Thank you, now it works!

```
Reading "genres.list.gz" to find interesting movies
Found 213914 titles
Writing "titles.csv"
Finished writing "titles.csv"
Reading release dates from "release-dates.list.gz"
Finished writing "release_dates.csv"
Reading 'actors.list.gz'
Reading 'actresses.list.gz'
Finished writing "cast.csv"
```

Also, could you explain what went wrong?

**Comment by brandon-rhodes** [comment]
I must have always ran the script as either `python build/build.py` or, once in the directory, as `python ./build.py` — and I did not realize that, as soon as someone tried just `build.py`, that the parent directory would be just the empty string `''` which results in the error that you got.

The solution is to call `abspath()` so that, no matter how abbreviated the path is when the user types it, it gets turned into a full path like `/home/brandon/pandas-tutorial/build/build.py` or whatever that `dirname()` can get a useful result from when it chops the filename off.

**Comment by pauldevos** [comment]
Are the data files no longer available?

I attempted to download them, but they all failed when trying to "save link as"...

Update:

It could be because they're no longer supported or I need to download an FTP connector and somehow link to their site here: http://www.imdb.com/interfaces

**Comment by pauldevos** [comment]
Brandon,

I got them to work yesterday evening, but again receiving an error - so might just be a spotty service aspect on their part. 

## Error Message:

The server at ftp.fu-berlin.de is taking too long to respond.

```
The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer's network connection.
If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
```

---

Thanks for re-opening, but may be only addressable from IMDB side of things and perhaps for users to try during non-peak hours.

**Comment by brandon-rhodes** [comment]
That does look like an IMDB problem, so I am going to close this issue unless we discover otherwise. Thanks!
