### ISSUE TITLE
dataframe sort() doesn't exist any more

### ISSUE THREAD

**Issue by sandipb** [brandon-rhodes/pycon-pandas-tutorial#40]
(I have consistently touted this as one of the best tutorials in any topic in programming that I have read. I keep coming back to this every time I have been away from Pandas for a while and have to refresh my memory. Thanks for ever for doing this.)

Perhaps an errata would be helpful to correct for the API changes that have happened so far.

For one, I found out that dataframe `.sort()` doesnt exist any more and `.sort_values()` should be used instead.

**Comment by brandon-rhodes** [comment]
Thank you! :)   — I'll go back through the notebooks, maybe this weekend, and get them updated and working again. Thanks for pointing out that they've gone out of date! Since they have no tests, there's nothing to alert me when a method they use stops existing.

Fun historical fact: I myself had actually wanted the method to be named "sorted()"

https://github.com/pandas-dev/pandas/issues/9816

**Comment by brandon-rhodes** [comment]
This was resolved, it looks like, in ae4a0e8c0de590f71da7d8d495dae4a4e5785f7e — so a fresh checkout of the project should assure that you have up-to-date Pandas code. Thanks again for the kind words, and I'm glad the tutorial has been helpful to you!

**Comment by ReddyKilowatt** [comment]
I too am having fun with these notebooks and datasets. This is my first look into data analysis. I was planning on submitting a PR with the notebook updates for recent Pandas, but decided not to. Some people may be using older Pandas, while  others like myself are using the latest. I’m not sure the best way to cover both without breaking anything.

**Comment by brandon-rhodes** [comment]
Yes, my approach for the moment is to edit code where necessary but otherwise to not disturb the JSON as long as it keeps working on the most recent version of Pandas!
