### ISSUE TITLE
Is this tutorial up to date?

### ISSUE THREAD

**Issue by vasili111** [brandon-rhodes/pycon-pandas-tutorial#47]
I just see that it was created in 2015.

**Comment by kollaesch** [comment]
Hi,
no need to create an issue - just read.
As pointed out in the other open issue there are some problems that occured due to old data.

I'd say - The repo combined with the [youtube-video](https://www.youtube.com/watch?v=5JnMutdy6Fw) it's still are very good resource in my opinion.

ps: thanks for your work on AHK

**Comment by vasili111** [comment]
@kollaesch Thank you :)
