### ISSUE TITLE
Can we remove redundant exercises?

### ISSUE THREAD

**Issue by siraj-samsudeen** [brandon-rhodes/pycon-pandas-tutorial#50]
Hi Brandon,

Appreciate your time and effort in coming up with so many exercises for us to practice. However, it would beneficial if the exercises are not repetitive - for example, out of these 2 questions, only 1 can be kept. 

# How many movies were made in the year 1950?
len(titles[titles.year == 1950])
# How many movies were made in the year 1960?
len(titles[titles.year == 1960])

every exercise should contain something new so that my time as a student practising is well-spent. When there are repetitions, I feel that I should stop doing more exercises, but there are some valuable exercises at the bottom which test different things - hence I would NOT want to miss out on them.

**Comment by brandon-rhodes** [comment]
> However, it would beneficial if the exercises are not repetitive …

My impression is that the academic research on learning has found repetition to be valuable, especially when someone is learning a completely novel skill. Which would agree with my own experience, at least. Cases where there are two or three similar examples in a row are designed to help the student master a new maneuver and also give them the confidence that comes through repeating a success a few times before going on to a new challenge.

But if you think that the particular example you give will hurt students, I'm open to considering an argument, but please cite studies of education arguing against repetition in cases like this. Given everything I know about teaching, eliminating the example you cite will make the lesson worse?

When — for example — I have sat in one of Raymond Hettinger's Python classes, and it involved repetition, I didn't consider my time not "well-spent". Doing something new for the second time is often nearly as perilous as doing it the first time.

**Comment by siraj-samsudeen** [comment]
Hi Brandon, thank you so much for such a detailed response. I don't have any research studies that say repetition is not helpful. Repeition is very helpful, I agree 100%. And it is not so serious :) - I just felt that repetition without any new value added was not helping me. It is a just personal opinion and I fully hear and understand your experience with your python classes. 

Please note that my aim is not to argue with you, but to invite yourself to think about my opinion a little bit more - you in the teacher role and me in the student role so the other students could benefit more from your teaching. 

1. I use repetition quite a bit in my studies - your videos of 2.5 hours length, I have spent around 10 hours or more and I visit and revisit the ideas over the course of a few days so that I repeat the ideas consciously. 
2. I use SRS system to do more repetition over a period of time - here is a great article on this topic full of golden insights - https://sivers.org/srs
3. I wrote down questions about things I did not understand, areas where I still had confusions, and revisited your video  and cleared up some of them. 
4. As part of this, I was visiting and revisiting the exercises - that is where I found the exercises which are exactly the same to be less value-adding than the others. There is no doubt that doing even these exercises build up muscle memory.
5. As a person interested in teaching, I do read and experiment quite a bit - when I set exercises, I try to see each new exercise adds something to the previous **to keep the interest level high** - if you have not read the great book 'Made to Stick' by Dan and Chip Heath, I recommend that you read this book, if you have not read it already, where I have found a lot of insights related to teaching and better communication. This is the key reason - repetition might cause some students to lose interest and stop in the middle or skip some exercises thinking it is the same whereas you might have a trick/tip hidden in that. As a student, I am diligent and try to do everything that the teacher says so that I take it all in - but I have seen a lot of students with little attention span and my suggestion might help them. 

I just want to reiterate again that I loved your teaching and the effort you have put in to maintain the exercises current till-date over the last 5 years. My aim is to help improve this - since written message does not convey the tone properly, I am adding these caveats. 

Have a nice day Brandon.

**Comment by brandon-rhodes** [comment]
Thank you for the extended and thoughtful response! And for the detailed glimpse into how you, as one particular learner, tackle online materials where you need to pace yourself through them without a live instructor, and get your own questions answered. I will search for the "Made to Stick" book at the local library.

I am going to close this issue for now because I'm not inclined at the moment to tweak the exercises — especially since folks follow them while watching the old video of me teaching, I would rather that they match was I was doing back then.

But — maybe at some point I should think about going through and, instead of just removing or tweaking this one question, thoroughly revise the exercises. Now that the original tutorial is over, they no longer need to be limited to what I thought could fit into 3 hours. Instead I could add additional stepping stones, provide more small incremental steps, and, as you suggest here, try pivoting questions where are sheer repetitions so that there's some additional twist or lesson. I would have to think about whether to record new videos to go with them, or instead to make written materials — maybe inline right in the notebooks — that would introduce each concept before having the student try them out.

But until I have time for a more thorough rewrite, I'm going to leave it as-is. So, closing this for the moment, but will definitely be referring back to this issue the next time I have the time for a rewrite — so, thanks for the ideas!

**Comment by siraj-samsudeen** [comment]
Thank you Brandon for the detailed response. I agree with you. Please take
it up when you have time
Kind Regards,
Siraj, Chennai.
+91 97 899 68 576

**Comment by siraj-samsudeen** [comment]
Hi Brandon,

I went back to this tutorial almost after a 3 years gap - I have been using
pandas on and off over these years and I wanted a full refresher as I was
embarking on some hard tasks using Pandas and I thought a good complete
refresher would be good. I really enjoyed every minute of your session - so
thoughtful and so playful. I love teaching and there is a lot of ideas I
can pick up from you, on my 2nd run with your videos. Thank you so much
Brandon.

I wish you could put together a series on Groupby - especially the more
advanced areas of groupby which equate to having clause in SQL and to join
information back from the group by to the original rows, etc.

Have a wonderful day Brandon.

Regards,
Siraj from Chennai, India

**Comment by brandon-rhodes** [comment]
@siraj-samsudeen — I'm glad that you found the tutorial (again) helpful! If I get time to expand it or produce another one in the future, I'll keep in mind that groupby would be a good topic.
