### ISSUE TITLE
Data file missing

### ISSUE THREAD

**Issue by Balupc** [brandon-rhodes/pycon-pandas-tutorial#57]
date file missing

**Comment by brandon-rhodes** [comment]
Which file?

**Comment by Balupc** [comment]
> Which file?

The "Data" file has been removed by IMDB. Kindly share the same if you have any copies.

**Comment by brandon-rhodes** [comment]
It's been a while since I have looked at this project, but I don't remember its using a file named "Data". Could you point out which part of the documentation, or which script, mentions that file?

**Comment by 4722794** [comment]
Hi @Balupc, the `data` folder is not available with the repo but if you check `README.md` there are instructions which you can follow to download the files and create it. 
Specifically look at the `build/BUILD.sh` shell script. (I recently tested it and it works)

@brandon-rhodes, Hi! you're my programming hero! Your videos are a treat to watch. Thank you for making the concepts fun and interesting.

**Comment by brandon-rhodes** [comment]
@4722794 — Thanks for offering that suggestion! You're probably correct that the question was about the `data/` directory; since I happen to be on a filesystem that's case-sensitive, I forgot that `Data` and `data` are the same on many folks' computers. It hadn't occurred to me that @Balupc might not have seen the `README.md`, but it would explain why the folder isn't built yet. I'll go ahead and close the issue in the hope that you've identified the problem.

And thank you _very_ much for the kind words—I'll do my best to continue making concepts fun and interesting!

**Comment by MKhizerButt** [comment]
For anyone still facing issues downloading the files, simply access the following link: ftp://ftp.fu-berlin.de/misc/movies/database/frozendata/ on your windows explorer and download the files separately then add them to a folder and name it Data.
