### ISSUE TITLE
Exercises-3 Solution | Use groupby() to determine how many roles are listed for each of the Pink Panther movies.

### ISSUE THREAD

**Issue by NMGIS** [brandon-rhodes/pycon-pandas-tutorial#58]
Hey Brandon. Great tutorial, and you're an excellent teacher. 

The solution provided for the above mentioned solution is: 

```
c = cast
c = c[c.title == 'The Pink Panther']
c = c.sort_values('n').groupby(['year'])[['n']].max()
c

```

result: 
	n
year	
1963	15
2006	50

However, in effort to include all Pink Panther movies.. I think it should be:

```
c = cast
c = c[c.title.str.contains("Pink Panther")]
c.groupby(['title', 'year']).n.max()

```
result: 

title                           year
Curse of the Pink Panther       1983    63.0
Revenge of the Pink Panther     1978    57.0
Son of the Pink Panther         1993    43.0
The Pink Panther                1963    15.0
                                2006    50.0
The Pink Panther 2              2009    36.0
The Pink Panther Strikes Again  1976    60.0
The Return of the Pink Panther  1975    27.0
Trail of the Pink Panther       1982    32.0
Name: n, dtype: float64

Overall, I think it depends on the questions phrasing. If the question is focused only on "The Pink Panther", the "T" in "The" needs capitalized in the question. Thanks again.

**Comment by NMGIS** [comment]
Video explains "The Pink Panther"

**Comment by brandon-rhodes** [comment]
> Hey Brandon. Great tutorial, and you're an excellent teacher.

Thank you, I'm glad that you found it useful! I'm glad that listening to the tutorial itself helped clarify the question about _The Pink Panter_ movie and its remake. But since not everyone is likely to listen to the entire tutorial, I think it does make sense to re-word the question a little; so, as you can see from the above commit, I've re-worded the question for greater clarity. Hopefully this helps future readers!
